import 'package:get/get.dart';
import 'package:travelzilla_dubai_flutter/model/ticket.dart';

class FlightTicketWidgetController extends GetxController {
  RxList<FlightTicketsWidget> ticketItems = <FlightTicketsWidget>[
    FlightTicketsWidget(
        title: "EXPLORE DUBAI",
        fromTime: "AUG 20",
        fromDate: "5:35 AM",
        arriveDate: "AUG 20",
        arriveTime: "12:30 PM",
        destination: "DXB",
        elapsedTime: "11h 00m",
        isRunning: true,
        origin: "U.A.E."),
    FlightTicketsWidget(
        title: "VACATION IN SHARJAH",
        fromTime: "MAR 12",
        fromDate: "8:35 AM",
        arriveDate: "MAR 12",
        arriveTime: "10:30 PM",
        destination: "SHJ",
        elapsedTime: "09h 00m",
        isRunning: true,
        origin: "U.A.E."),
    FlightTicketsWidget(
        title: "BIZ TRIP TO ABU DHABI",
        fromTime: "MAY 8",
        fromDate: "7:35 AM",
        arriveDate: "MAY 8",
        arriveTime: "1:30 PM",
        destination: "AUH",
        elapsedTime: "014h 00m",
        isRunning: true,
        origin: "U.A.E."),
    FlightTicketsWidget(
        title: "VACATION IN FUJAIRAH",
        fromTime: "JUL 30",
        fromDate: "6:35 AM",
        arriveDate: "JUL 30",
        arriveTime: "11:30 PM",
        destination: "FUJ",
        elapsedTime: "08h 00m",
        isRunning: false,
        origin: "U.A.E."),
    FlightTicketsWidget(
        title: "VACATION IN OMAN",
        fromTime: "OCT 2",
        fromDate: "4:20 AM",
        arriveDate: "OCT 2",
        arriveTime: "10:30 PM",
        destination: "OMN",
        elapsedTime: "09h 00m",
        isRunning: false,
        origin: "U.A.E."),
    FlightTicketsWidget(
        title: "VACATION IN AL-AIN",
        fromTime: "DEC 12",
        fromDate: "5:35 AM",
        arriveDate: "DEC 12",
        arriveTime: "12:30 PM",
        destination: "AIN",
        elapsedTime: "012h 00m",
        isRunning: false,
        origin: "U.A.E."),
    FlightTicketsWidget(
        title: " FIND PIECE IN BAHRIN",
        fromTime: "MAR 5",
        fromDate: "5:35 AM",
        arriveDate: "MAR 5",
        arriveTime: "9:30 PM",
        destination: "BARH",
        elapsedTime: "08h 00m",
        isRunning: true,
        origin: "U.A.E."),
    FlightTicketsWidget(
        title: "VACATION IN RAS-AL-KHAIMAH",
        fromTime: "FEB 10",
        fromDate: "5:35 AM",
        arriveDate: "FEB 10",
        arriveTime: "8:30 PM",
        destination: "RAK",
        elapsedTime: "010h 00m",
        isRunning: true,
        origin: "U.A.E."),
    FlightTicketsWidget(
        title: "VACATION IN BAKU",
        fromTime: "JAN 1",
        fromDate: "7:30 AM",
        arriveDate: "JAN 1",
        arriveTime: "10:30 PM",
        destination: "BAK",
        elapsedTime: "012h 00m",
        isRunning: false,
        origin: "U.A.E."),
    FlightTicketsWidget(
        title: "VACATION IN EGYPT",
        fromTime: "JUN 9",
        fromDate: "6:35 AM",
        arriveDate: "JUN 9",
        arriveTime: "12:30 PM",
        destination: "ARN",
        elapsedTime: "016h 07m",
        isRunning: true,
        origin: "ARN"),
  ].obs;
}
